# Generated by Django 3.0.3 on 2020-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0002_auto_20200305_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
