# Generated by Django 3.0.3 on 2020-05-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0004_auto_20200501_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
